package corejava_part3;
import java.util.Scanner;
import java.io.FileReader;
public class Exception1 
{
	void meth()
	{
		Scanner sc=new Scanner(System.in);
		System.out.println("this is start");
		String names[]=new String[5];
		names[1]="ram";
		names[3]="shyam";
		try
		{
			System.out.println("enter a number: ");
			System.out.println("===>"+20/sc.nextInt());
			System.out.println("Length: "+names[2].length());
		}
		/*
		catch(ArithmeticException e)
		{
			System.out.println("1st catch block executed");
			e.printStackTrace();
		}
		catch(NullPointerException e)
		{
			System.out.println("2nd catch block");
			e.printStackTrace();
		}
		*/
		catch(ArithmeticException | NullPointerException e)
		{
			System.out.println("this is one catch block");
			e.printStackTrace();
		}
		finally
		{
			System.out.println("final block executed");
			sc.close();		}
	}
	
	void meth2() throws Exception
	{
		System.out.println("meth2 called");
		try(FileReader fr=new FileReader("C:\\Users\\DRYDEN\\Documents\\file.txt"))
		{
			System.out.println("connection created");
		}
	}
	public static void main(String[] args) throws Exception
	{
		//new Exception1().meth();
		new Exception1().meth2();
	}

}
